function C = Euler2Dcm(phi, theta, psi)
if nargin < 3
    psi = phi(3);
    theta = phi(2);
    phi = phi(1);
end
Rx=[1 0 0; ...
    0 cos(phi) sin(phi);...
    0 -sin(phi) cos(phi)];
Ry=[cos(theta) 0 -sin(theta);...
    0 1 0;...
    sin(theta) 0 cos(theta)];
Rz=[cos(psi) sin(psi) 0;...
    -sin(psi) cos(psi) 0;...
    0 0 1];
Rx(abs(Rx)<eps) = 0;
Ry(abs(Ry)<eps) = 0;
Rz(abs(Rz)<eps) = 0;
C = Rx*Ry*Rz;