function [loggingTime,a,g] = importIphoneImuFile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [LOGGINGTIME1,LOGGINGSAMPLE1,ACCELEROMETERTIMESTAMP_SINCEREBOOT1,ACCELEROMETERACCELERATIONX1,ACCELEROMETERACCELERATIONY1,ACCELEROMETERACCELERATIONZ1,GYROTIMESTAMP_SINCEREBOOT1,GYROROTATIONX1,GYROROTATIONY1,GYROROTATIONZ1]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [LOGGINGTIME1,LOGGINGSAMPLE1,ACCELEROMETERTIMESTAMP_SINCEREBOOT1,ACCELEROMETERACCELERATIONX1,ACCELEROMETERACCELERATIONY1,ACCELEROMETERACCELERATIONZ1,GYROTIMESTAMP_SINCEREBOOT1,GYROROTATIONX1,GYROROTATIONY1,GYROROTATIONZ1]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [loggingTime1,loggingSample1,accelerometerTimestamp_sinceReboot1,accelerometerAccelerationX1,accelerometerAccelerationY1,accelerometerAccelerationZ1,gyroTimestamp_sinceReboot1,gyroRotationX1,gyroRotationY1,gyroRotationZ1]
%   = importfile('2015-04-22_16-33-47.csv',2, 633);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/04/22 16:41:28

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
loggingTime = dataArray{:, 1};
loggingSample = dataArray{:, 2};
accelerometerTimestamp_sinceReboot = dataArray{:, 3};
accelerometerAccelerationX = dataArray{:, 4};
accelerometerAccelerationY = dataArray{:, 5};
accelerometerAccelerationZ = dataArray{:, 6};
gyroTimestamp_sinceReboot = dataArray{:, 7};
gyroRotationX = dataArray{:, 8};
gyroRotationY = dataArray{:, 9};
gyroRotationZ = dataArray{:, 10};

a = [accelerometerTimestamp_sinceReboot accelerometerAccelerationX accelerometerAccelerationY accelerometerAccelerationZ];
g = [gyroTimestamp_sinceReboot gyroRotationX gyroRotationY gyroRotationZ];


